name: Add Glucose Entry

on:
  workflow_dispatch:
    inputs:
      value:
        required: true
      datetime:
        required: true
      reldatetime:
        required: false
      unit:
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install nl locale
      run: |
        cd /usr/share/locales
        sudo ./install-language-pack nl_NL
        sudo dpkg-reconfigure locales
    - name: Generate web page from template
      run: |
        python3 convert.py \
          "${{ github.event.inputs.value }}" \
          "${{ github.event.inputs.datetime }}"
    - name: Commit html page
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: New glucose entry
        file_pattern: public/index.html
        push_options: '--force'
        branch: build
        create_branch: true
